import { readFile, writeFile } from 'node:fs/promises';
import { createClientPlugin } from './client-source.mjs';
import { createBrandComponents } from './brand-source.mjs';
import { buildBrandAssets } from '../../scripts/build-brand-assets.mjs';
import { createPageStage } from './stage-source.mjs';
import { buildPageDocument } from './page-document.mjs';
import { createPageSubmitter } from './page-submit.mjs';
import { createInteractionComponents } from './interaction-source.mjs';
import { createInteractionSubmitter } from './interaction-submit.mjs';
import { createWorkspaceModel } from './workspace-model.mjs';
import { createMotionRuntime } from './motion-source.mjs';
import { createFrostComponents } from './frost-source.mjs';
import { createSessionControls } from './session-controls-source.mjs';
import { createAttachmentComponents } from './attachment-source.mjs';
import { createActivityComponents } from './activity-source.mjs';
import { createTerminalComponents } from './terminal-source.mjs';
import { createFileViewComponents } from './file-view-source.mjs';
import { createHtmlPreviewComponents } from './html-preview-source.mjs';
import { createPdfViewComponents } from './pdf-view-source.mjs';
import { buildPdfBundle } from './build-pdf.mjs';
import { createWorkbenchPane } from './workbench-pane-source.mjs';
import { createComputerComponents } from './computer-source.mjs';
import { createModelControlComponents } from './model-control-source.mjs';
import { createMenuCatalog } from './menu-catalog-source.mjs';
import { createMarketplaceComponents } from './marketplace-source.mjs';
import { createSuperpowersComponents } from './superpowers-source.mjs';
import { createUsageComponents } from './usage-source.mjs';
import { createUpdateComponents } from './updates-source.mjs';
import { createWorkspaceShell } from './workspace-shell-source.mjs';
import { createCompanionComponents } from './companion-source.mjs';
import { buildCompanionAsset } from '../../scripts/build-companion-asset.mjs';

// DSH rc.2 consumes lazy CJS factory registration, not browser ESM imports.
await buildPdfBundle();
const brandAssets = await buildBrandAssets();
const companionAsset = await buildCompanionAsset();
const css = (await Promise.all(['coldx.css', 'native.css', 'interaction.css', 'frost.css', 'attachment.css', 'activity.css', 'terminal.css', 'layout.css', 'workbench.css', 'file-view.css', 'pdf-view.css', 'computer.css', 'ui-consistency.css', 'composer.css', 'model-control.css', 'marketplace.css', 'brand.css', 'superpowers.css', 'usage.css', 'updates.css', 'workspace-shell.css', 'companion.css'].map(path => readFile(new URL(path, import.meta.url), 'utf8')))).join('\n');
const factories = { brand: createBrandComponents, workspaceShell: createWorkspaceShell, stage: createPageStage, document: buildPageDocument, pageSubmit: createPageSubmitter,
  interactions: createInteractionComponents, interactionSubmit: createInteractionSubmitter, workspaceModel: createWorkspaceModel, motion: createMotionRuntime, frost: createFrostComponents, sessionControls: createSessionControls, attachments: createAttachmentComponents,
  activity: createActivityComponents, terminal: createTerminalComponents, files: createFileViewComponents, htmlPreview:createHtmlPreviewComponents, pdf:createPdfViewComponents, workbenchPane:createWorkbenchPane, computer:createComputerComponents, modelControl:createModelControlComponents, menuCatalog:createMenuCatalog, marketplace:createMarketplaceComponents, superpowers:createSuperpowersComponents, usage:createUsageComponents, updates:createUpdateComponents };
factories.companion = createCompanionComponents;
const args = `{${Object.entries(factories).map(([key, fn]) => key === 'companion'
  ? `${key}:(React,settings)=>(${fn.toString()})(React,settings,${JSON.stringify(companionAsset)})`
  : key === 'brand'
  ? `${key}:(React)=>(${fn.toString()})(React,${JSON.stringify(brandAssets)})`
  : `${key}:(${fn.toString()})`).join(',\n')}}`;
const output = `// Generated by node plugin/client/build.mjs.\nwindow.__ModuleLoader__.load({\n  id: 'coldx-client',\n  factory(require) { return (${createClientPlugin.toString()})(require('react'), require('@deepseek-ai/dsh-client-ui-primitives'), ${args}, ${JSON.stringify(css)}); }\n});\n`;
await writeFile(new URL('./client.js', import.meta.url), output);
