// Generated by plugin/client/build.mjs.
window.__ModuleLoader__.load({id:'@deepseek-ai/dsh-client-ui-sidebar',factory(require){
const {Sidebar}=(function createWorkbenchShell(React) {
  const h = React.createElement;
  const paths = {
    search:'m21 21-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0', clock:'M12 7v5l3 2 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',
    branch:'M6 5v14 M6 9h8a4 4 0 0 0 4-4 M4 3h4v4H4z M4 17h4v4H4z M16 3h4v4h-4z',
    more:'M4 12h1 M11 12h1 M18 12h1', folder:'M3 6h7l2 2h9v12H3z', pin:'m9 3 6 0-1 6 4 4H6l4-4z M12 13v8',
    archive:'M3 3h18v5H3z M5 8v13h14V8 M9 12h6', copy:'M8 8h13v13H8z M3 16V3h13',
    plugin:'M12 3a9 9 0 1 0 9 9 M17 7a5 5 0 1 0 0 8V7z M17 15c0 4 5 4 5-2V9',
    chart:'M4 3v18h17 M8 15v-5 M13 17V7 M18 15v-5', refresh:'M20 7v5h-5 M4 17v-5h5 M6 7a7 7 0 0 1 11-1l3 3 M4 15l3 3a7 7 0 0 0 11-1',chat:'M3 3h18v14H9l-6 4z',
    panel:'M3 3h18v18H3z M9 3v18', edit:'M13 5H5v14h14v-8 M15 3l6 6 M11 13l2-5 5-5 3 3-5 5z',
    chevron:'m9 10 3 3 3-3', plus:'M12 5v14 M5 12h14', list:'M9 5h11 M9 12h11 M9 19h11 M3 5h1 M3 12h1 M3 19h1',
    file:'M14 3H5v18h14V8z M14 3v5h5', link:'M10 14a5 5 0 0 0 7 0l3-3a5 5 0 0 0-7-7l-2 2 M14 10a5 5 0 0 0-7 0l-3 3a5 5 0 0 0 7 7l2-2',
    agent:'M12 3v3 M7 6h10a3 3 0 0 1 3 3v9H4V9a3 3 0 0 1 3-3z M8 11v2 M16 11v2 M9 16h6',
    globe:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M3 12h18 M12 3c5 5 5 13 0 18-5-5-5-13 0-18',
    terminal:'m5 7 5 5-5 5 M13 17h6', close:'m6 6 12 12 M18 6 6 18',
  };
  function icon(name) { return h('svg',{width:16,height:16,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.5,strokeLinecap:'round',strokeLinejoin:'round','aria-hidden':true},h('path',{d:paths[name]||paths.file})); }
  function Sidebar({collapsed,startSession,toggleSidebar,renderSlot,Navigation}) {
    const wide = !collapsed;
    return h('aside',{className:'cx-rebuild-sidebar','data-collapsed':collapsed,'aria-label':'主导航'},
      h('div',{className:'cx-rebuild-brand-row'},
        wide && h('button',{type:'button',className:'cx-rebuild-brand','aria-label':'ColdX 首页',onClick:()=>startSession()},
          h('span',{className:'cx-rebuild-brand-mark','aria-hidden':true},h('span',null,'C'),h('i')),
          h('span',{className:'cx-rebuild-brand-name'},'ColdX')),
        h('button',{type:'button',className:'cx-rebuild-icon','aria-label':wide?'收起侧边栏':'打开侧边栏',title:wide?'收起侧边栏':'打开侧边栏',onClick:toggleSidebar},icon('panel'))),
      h('button',{type:'button',className:'cx-rebuild-nav','aria-label':'新对话',title:wide?undefined:'新对话',onClick:()=>startSession()},icon('edit'),wide&&h('span',null,'新对话')),
      Navigation && h(Navigation,{wide}),
      h('div',{className:'cx-rebuild-navigation'},renderSlot('sidebar.footer.action',{wide})),
      h('div',{className:'cx-rebuild-task-list'},renderSlot('sidebar.workspaces',{wide,expandSidebar:()=>{if(collapsed)toggleSidebar();}})),
      h('div',{className:'cx-rebuild-settings'},renderSlot('sidebar.settings',{wide})));
  }
  function Summary({sessionId,model,onOpenOutput,onOpenFile,onOpenSubagent,onOpenView}) {
    const [open,setOpen] = React.useState(()=>model?.visible!==false), [error,setError] = React.useState(null);
    const trigger = React.useRef(null), card = React.useRef(null);
    const close = restoreFocus => {setOpen(false);if(restoreFocus)trigger.current?.focus?.({preventScroll:true});};
    (React.useLayoutEffect??React.useEffect)(()=>{
      const owner=trigger.current?.closest?.('.wSkVaW_root');if(!owner)return;
      // A compact window starts with the drawer closed. At desktop width the
      // reader may deliberately leave it open; resizing never forces it back.
      const header=owner.querySelector('.wSkVaW_header');
      const fit=()=>{
        if(owner.clientWidth<960)setOpen(false);
        const ownerTop=owner.getBoundingClientRect().top;
        const headerBottom=header?.getBoundingClientRect().bottom??ownerTop+46;
        owner.style.setProperty('--cx-summary-top',`${Math.max(0,headerBottom-ownerTop)}px`);
      };fit();
      const resize=typeof ResizeObserver==='function'?new ResizeObserver(fit):null;
      resize?.observe(owner);
      if(header)resize?.observe(header);
      const hiddenByWorkbench=()=>{if(owner.querySelector('.cx-workbench-panel[open]'))setOpen(false);};
      const changes=typeof MutationObserver==='function'?new MutationObserver(hiddenByWorkbench):null;
      changes?.observe(owner,{subtree:true,childList:true,attributes:true,attributeFilter:['open']});
      hiddenByWorkbench();
      return()=>{resize?.disconnect();changes?.disconnect();};
    },[]);
    React.useEffect(()=>{
      if(!open)return;
      const onEscape=event=>{
        const focused=document.activeElement;
        if(event.key==='Escape'&&(card.current?.contains?.(focused)||trigger.current===focused))close(true);
      };
      document.addEventListener('keydown',onEscape);
      return()=>document.removeEventListener('keydown',onEscape);
    },[open]);
    const perform = operation => async () => {
      setError(null);
      try{await operation?.();close(false);}catch(problem){setError(problem?.message||'操作失败，请重试。');}
    };
    const outputs=(model?.outputs??[]).filter(item=>item.category!=='process'&&item.operation!=='delete');
    const agents=model?.subagents??[], source=model?.sources??{web:[],workspace:[],session:[]};
    const computers=model?.computers??[],terminals=model?.terminals??[];
    const now=model?.now??{kind:'idle',text:'查看本次行动与证据',status:'unknown',tone:'neutral'};
    const running=agents.filter(item=>item.status==='running').length;
    const completed=agents.filter(item=>item.status==='completed').length;
    const failed=agents.filter(item=>item.status==='failed').length;
    const sourceRows=[
      ...(source.web??[]).map(item=>({key:item.key,label:item.title||item.domain,subtitle:item.domain,href:item.url,glyph:'globe'})),
      ...(source.workspace??[]).map(item=>({key:item.key,label:item.path,subtitle:item.line?`第 ${item.line} 行`:'工作区文件',glyph:'file',action:onOpenFile?()=>onOpenFile(item.path,item.line):undefined})),
      ...(source.session??[]).map(item=>({key:item.key,label:item.label,subtitle:'引用的会话',glyph:'chat',action:onOpenView?()=>onOpenView('evidence'):undefined})),
    ];
    const sectionHeading=(label,view,count)=>h('div',{className:'cx-rebuild-summary-heading'},
      h('h3',null,label),
      h('span',{className:'cx-summary-heading-actions'},
        count>0&&h('span',{className:'cx-summary-count'},count),
        view&&h('button',{type:'button',className:'cx-summary-text-action',onClick:perform(()=>onOpenView?.(view)),disabled:!onOpenView,'aria-label':`查看全部${label}`},'查看全部',icon('chevron'))));
    const row=({label,subtitle,glyph='file',status,props={}})=>h('button',{type:'button',className:'cx-rebuild-summary-row',...props},
      h('span',{className:'cx-summary-row-icon'},icon(glyph)),
      h('span',{className:'cx-summary-row-copy'},h('span',{className:'cx-summary-row-title'},label),subtitle&&h('span',{className:'cx-summary-row-detail'},subtitle)),
      status&&h('span',{className:'cx-summary-row-status'},status));
    return h('div',{className:'cx-rebuild-summary-root'},
      h('button',{type:'button',ref:trigger,className:'cx-rebuild-icon','aria-label':'任务摘要','aria-expanded':open,'aria-controls':`cx-task-summary-${sessionId}`,onClick:()=>setOpen(value=>!value)},icon('list')),
      open&&h('button',{type:'button',className:'cx-rebuild-summary-scrim','aria-label':'关闭任务摘要',onClick:()=>close(true)}),
      open&&h('aside',{ref:card,id:`cx-task-summary-${sessionId}`,className:'cx-rebuild-summary','aria-label':'任务摘要','data-open':'true',onKeyDown:event=>{if(event.key==='Escape'){event.stopPropagation();close(true);}}},
        h('div',{className:'cx-summary-header'},h('div',null,h('span',{className:'cx-summary-eyebrow'},'本次会话'),h('h2',null,'任务摘要')),
          h('button',{type:'button',className:'cx-rebuild-icon','aria-label':'关闭任务摘要',onClick:()=>close(true)},icon('close'))),
        h('div',{className:'cx-summary-scroll'},
          h('section',{className:'cx-summary-now','aria-label':'当前状态','data-tone':now.tone},
            h('span',{className:'cx-summary-live-mark','aria-hidden':true}),
            h('div',{className:'cx-summary-now-copy'},
              h('span',{className:'cx-summary-now-label'},now.status==='running'?'正在执行':now.status==='waiting'?'等待操作':'最近进展'),
              h('strong',null,now.text)),
            h('button',{type:'button',className:'cx-summary-now-link','aria-label':'查看任务进度',onClick:perform(()=>onOpenView?.('timeline')),disabled:!onOpenView},icon('chevron'))),
          (model?.counts?.calls>0)&&h('p',{className:'cx-summary-tool-count'},`${model.counts.calls} 次工具调用`),
          h('section',{className:'cx-summary-section','aria-label':'产物'},sectionHeading('产物','files',outputs.length),
            outputs.length?outputs.slice(-5).reverse().map(item=>row({label:item.label||item.path?.split(/[\\/]/).pop()||item.title||'生成页面',
              subtitle:item.kind==='page'?'页面':item.path, glyph:item.kind==='page'?'panel':'file',status:item.statusLabel,
              props:{key:item.key,title:item.path||item.title,'aria-label':`打开 ${item.label||item.path||item.title}`,onClick:perform(()=>onOpenOutput?.(item)),disabled:!onOpenOutput}})):
              h('p',{className:'cx-rebuild-summary-empty'},'暂无产物。创建文件或页面后会显示在这里。')),
          agents.length>0&&h('section',{className:'cx-summary-section','aria-label':'子智能体'},sectionHeading('子智能体','timeline',agents.length),
            h('p',{className:'cx-rebuild-agent-count'},running?`${running} 个运行中`:`${agents.length} 个子智能体`,
              [completed?`${completed} 完成`:null,failed?`${failed} 失败`:null].filter(Boolean).length&&h('span',null,[completed?`${completed} 完成`:null,failed?`${failed} 失败`:null].filter(Boolean).join(' · '))),
            agents.slice(0,4).map(agent=>row({label:agent.label,subtitle:agent.statusLabel,glyph:'agent',
              props:{key:agent.key,title:agent.statusLabel,'aria-label':`打开子智能体 ${agent.label}`,
                disabled:agent.kind!=='child'||agent.disabled||!onOpenSubagent,
                onClick:perform(()=>onOpenSubagent?.({parentSessionId:sessionId,childSessionId:agent.id,mode:agent.mode}))}}))),
          computers.length>0&&h('section',{className:'cx-summary-section','aria-label':'电脑使用'},sectionHeading('电脑使用','browser',computers.length),
            row({label:computers.at(-1).surfaceLabel,subtitle:'查看操作过程',glyph:'panel',status:computers.at(-1).status==='running'?'进行中':undefined,
              props:{'aria-label':'查看浏览器与电脑',onClick:perform(()=>onOpenView?.('browser')),disabled:!onOpenView}})),
          terminals.length>0&&h('section',{className:'cx-summary-section','aria-label':'命令记录'},sectionHeading('命令记录','timeline',terminals.length),
            row({label:terminals.at(-1).title,subtitle:'终端输出',glyph:'terminal',status:terminals.at(-1).status==='failed'?'失败':'已结束',
              props:{'aria-label':'查看命令记录',onClick:perform(()=>onOpenView?.('timeline')),disabled:!onOpenView}})),
          h('section',{className:'cx-summary-section','aria-label':'来源'},sectionHeading('来源','evidence',sourceRows.length),
            sourceRows.length?sourceRows.slice(0,5).map(item=>item.href?h('a',{className:'cx-rebuild-summary-row',key:item.key,href:item.href,target:'_blank',rel:'noopener noreferrer',title:item.label},
              h('span',{className:'cx-summary-row-icon'},icon(item.glyph)),
              h('span',{className:'cx-summary-row-copy'},h('span',{className:'cx-summary-row-title'},item.label),h('span',{className:'cx-summary-row-detail'},item.subtitle))):
              row({label:item.label,subtitle:item.subtitle,glyph:item.glyph,props:{key:item.key,title:item.label,'aria-label':`打开 ${item.label}`,onClick:perform(item.action),disabled:!item.action}})):
              h('p',{className:'cx-rebuild-summary-empty'},'读取文件或网页后会显示来源。')),
          error&&h('p',{className:'cx-rebuild-summary-error',role:'alert'},error))));
  }
  return {Sidebar,Summary,icon};
})(require('react'));
return {inject:['slots','layout','workspaces'],apply(ctx){ctx.slots.inject('sidebar',()=>ctx.slots.register({name:'sidebar',children:{'sidebar.brand.mark':{kind:'single',scope:'root'},'sidebar.brand.name':{kind:'single',scope:'root'},'sidebar.workspaces':{kind:'single',scope:'root'},'sidebar.settings':{kind:'single',scope:'root'},'sidebar.footer.action':{kind:'list',scope:'root'}},inject:()=>({startSession:id=>{ctx.get("coldxNavigation")?.start();ctx.workspaces.startSession(id)},toggleSidebar:()=>ctx.layout.toggleSidebar()})},Sidebar));}};}});
